server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sys_api_route
          uri: lb://sys-api
          predicates:
            - Path=/sys-api/**
          filters:
            - StripPrefix=1
        - id: scm_api_route
          uri: lb://scm-api
          predicates:
            - Path=/scm-api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/